### PR TITLE
Add .DS_Store to .gitignore and remove .DS_Store files

### PR DESCRIPTION
**Pull request by valentino-amadeus**
#### What is the purpose of this pull request?
- Add `.DS_Store` to `.gitignore`;
- Remove `.DS_Store` files.

#### How should this be manually tested?
No need to be tested.

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

### CODE REVIEW

**Review by victorges — COMMENTED** [review]
You seem to have way more changes than described in the PR title/description. Did you happen to forget to do a rebase or change the base branch of the PR on Github?

**Comment by valentino-amadeus** [comment]
The PR is based on the previous PR's branch (which in turn is based on its predecessor PR's branch, and so on and so forth; that's why all the commits). 
The previous PR contains all but the last two commits of this PR.

**Comment by victorges** [comment]
Oh, in that case, you can change the "base branch" of the PR so it only shows the difference click "Edit" in the top right of the PR and then in the dropdown that appears on the (current) `master` base branch, changing it to that predecessor PR branch you referred to. 
Screen Shot 2020-09-23 at 17 08 53

This will make github show only the actual diff between the 2 branches, so it makes it clearer for reviewers what is the actual change being proposed in each PR.

You will still need to do some `git rebase` tricks when actually merging the PRs though. In my case, I like doing a "master PR" to which I squash all the individual step-by-step PRs, and then merge this master PR with the `master` branch, like this one: https://github.com/vtex/apps/pull/379

A simpler approach is to merge each "step PR" separately directly to the master branch, but you will still require rebasing the proceeding PRs after merging each of the previous ones, as I believe there's unfortunately no automatic tool for that yet 😕

**Comment by valentino-amadeus** [comment]
Didn't know that. Thank you! :)

**Review by victorges — APPROVED** [review]
LGTM 😄

**Review by tergol1 — APPROVED** [review]

**Pull request merged**
